### ISSUE TITLE
Usage question ("Do I have to use Python to order spare parts")

### ISSUE THREAD

**Issue by hreyhani** [bittner/lego-mindstorms-ev3-comparison#12]
Question:
I have converted the .ods file to .xls and can see the list of  missing parts that I need to order.
Does one HAVE to use Python to order the spare parts? Can this be avoided? Any other option?
H

**Comment by bittner** [comment]
As described in the [Usage section](https://github.com/bittner/lego-mindstorms-ev3-comparison#usage) of the README:

> ... a Python3 script to help with calculating and ordering required LEGO Mindstorms EV3 spare parts.

You do _not_ have to use the Python script. You can of course fill in your order yourself on the LEGO shop site. Using the Python script is completely _optional_.

Advantages Of Using The Script For Ordering
------------------
Using the script saves to quite some time and pain in the ordering process, though, when you manage to use it, because the list of pieces you may want to order is huge! (See the [example order logs and screen shots](https://github.com/bittner/lego-mindstorms-ev3-comparison/tree/master/docs).)

What happens technically is:

1. the script opens the LEGO shop in a browser window,
1. logs in with the credentials you provide beforehand,
1. and puts in all the pieces into the LEGO shop order form.

You can watch the browser while this happens in a matter of seconds. The process will then stop in the end and allow you to complete the order process. (No actual order submission is performed; you have to complete the order yourself.)

Doing all this manually may take between 20 minutes and an hour, and make you possibly insane jumping back and forth, copy and pasting from the spread sheet, or typing off the printout you may have compiled or printed out. -- Make your choice!
