### ISSUE TITLE
unable to open spreadsheet

### ISSUE THREAD

**Issue by txcrude96** [bittner/lego-mindstorms-ev3-comparison#6]
I have downloaded the .ods file on two different machines and I am not able to open it in MS Excel 2010. I am getting an error that the file may be corrupt.

**Comment by txcrude96** [comment]
Update: was able to convert to .xls using free online service (Zamzar). Not sure if all the functionality remained but there are 3 tabs.

**Comment by bittner** [comment]
@txcrude96 Thanks for reaching out and for the feedback on using / importing the spread sheet.

Unfortunately, import problems with Microsoft products are out of my control. I don't even own a Microsoft Office license in order to test imports. Microsoft has a [support article](https://support.office.com/en-us/article/Use-Excel-to-open-or-save-a-worksheet-in-the-OpenDocument-Spreadsheet-ods-format-C7114BAA-F08A-49EB-AEFD-F5D61ED347CD) on this very topic, though.

I've added a note and a few links to the related section in the README so that other users can benefit from your feedback and from online services that convert ODS to other formats.

Thanks again!  :+1:
